README.md
install.js

```shell
npm install phantomjs --chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver
```

Support configure chromedriver cdn url via npm config property

---

.travis.yml
test-driver.sh

Still need to test on Linux, but I don't see any reason for it to fail.
timeout isn't supported on OS X and I couldn't find a solution that replicated the exit code the test was relying on.

Changing test to hopefully work on OS X

---

install.js

I use FreeBSD 10.2, and one of my web apps failed to build during an update because chromedriver hasn't yet added support. This little addition got me back up and running and I hope it helps someone else.

Add support for FreeBSD

---

README.md
install.js

In my client's environment we are not able to retrieve the chromedriver over the network. We are however able to get the chromedriver binary on the filesystem. 
This change allows the installer to take a local file as the source instead of requiring a download. 
It would be awesome if this feature became available.

Allow a file on the filesystem to be used as the source for the binary

---

install.js

Hi,
I've been trying to use the string CA option of node-chromedriver, however it doesn't work correctly. The format specified in the [npm documentation](https://docs.npmjs.com/misc/config) is ca="-----BEGIN CERTIFICATE-----\nXYZ1234.....", the current code leaves the newline and double quotes in and the certificate won't be sent correctly.
https://github.com/npm/npm/blob/2091dd1c748e54e85e904ce8da3b3975ee99117d/lib/config/core.js#L375-L381
As you can see in the npm source code above the correct way is to check if the string contains double quotes then run JSON.parse on it and then use it.
Enclosed is a pull request to fix the issue.

.npmrc ca option does not work correctly

---

install.js
package.json

When redirecting from https to http the protocol defined
on the request options caused a problem. We removed it and
let request infer the protocol.
Fixes #120

Fix https redirect

---

lib/chromedriver.js

Fixes #150.
Note that this PR attaches chromedriver's stdout/stderr to the parent process's. I couldn't get it to work any other way (but that's probably because of my limited knowledge of `child_process`). (I think that's kind of nice though, the current master just throws it away).

Start chromedriver using spawn instead of execFile

---

lib/chromedriver.js

This fixes an issue where if you had a globally installed copy of chromedriver (e.g. in /usr/local/bin), projects using this npm package would inadvertently end up using the global version rather than the one specified in their project's package.json file.

Add chromedriver to the beginning of PATH, rather than to the end

---

lib/chromedriver.js
package.json

Bump version to 2.42.
https://sites.google.com/a/chromium.org/chromedriver/downloads
https://chromedriver.storage.googleapis.com/index.html?path=2.42/
**Supports Chrome v68-70**
Changes include:
- Fixed ClickEelement in Mobile Emulation
- Fixed whitelisted IPs with IPv4
- Fixed starting ChromeDriver with whitelisted-ips flag on Mac OS
- Fixed SetTimeout to accept both pre-W3C and W3C formats
- Fixed take element screenshot
- Fixed ChromeDriver is looking for Chrome binaries in a system PATH as well
- Fixed Maximize window and Full Screen
- Implemented log-replay functionality. ( Does not work for Android and Remote Browser yet )
- Fixed some error codes were not compliant to W3C standard
- Fixed console.log with multiple arguments not handled properly
- Fixed GetElementRect should allow …

Bump ChromeDriver version to 2.42

---

install.js
package-lock.json

Updated install.js to support arm64 architecture. As chromedriver supports linux platform with 64 bits, arm64 architecture is a linux platform with 64 bits.
uname -a
Linux e7fac9d4ba1c 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux 
Please update the same for arm64 support.

adding arm64 support for chromedriver

---

README.md
install.js

This is an attempt at closing #139
This change allows users to use CHROMEDRIVER_FILEPATH to point to the
binary directly rather than just the zip file.
The change is transparent, for those using zip files nothing will change

Add support for binary file instead of just zip

---

README.md
install.js
lib/chromedriver.js

This is an attempt at closing #180 and possibly also #145
This adds the possibility to skip downloading the chromedriver binary
during installation, and fallback to the system binary when a local
binary is not found.

Add CHROMEDRIVER_SKIP_DOWNLOAD option

---

lib/chromedriver.js
package.json

**----------ChromeDriver v2.45 (2018-12-10)----------**
https://chromedriver.storage.googleapis.com/2.45/notes.txt
**Supports Chrome v70-72**
- Resolved issue 1997: New Session is not spec compliant [[Pri-1]]
- Resolved issue 2685: Should Assert that the chrome version is compatible [[Pri-2]]
- Resolved issue 2677: Find Element command returns wrong error code when an invalid locator is used [[Pri-2]]
- Resolved issue 2676: Some ChromeDriver status codes are wrong [[Pri-2]]
- Resolved issue 2665: compile error in JS inside of WebViewImpl::DispatchTouchEventsForMouseEvents [[Pri-2]]
- Resolved issue 2658: Window size commands should handle user prompts [[Pri-2]]
- Resolved issue 2684: ChromeDriver doesn't start Chrome correctly with options.addArguments("user-data-dir=") [[Pri-3]]
- …

Bump chromedriver version to 2.45

---

lib/chromedriver.js
package-lock.json
package.json

ChromeDriver 73.0.3683.20
- Supports Chrome version 73
- Fixed error code returned from Execute Script command in some scenarios
- Made the HTTP server keep connection alive by default
- Fixed Close Window command to correctly handle user prompts
- Fixed error code returned while sending keys to disabled element
- Improved spec compliance of timeout value handling
- Improved spec compliance of Add Cookie command
- Increased HTTP server listening queue length
- Fixed Is Element Displayed command in v0 shadow DOM
- Added warning about Element Clear command behavior change in log file
- Fixed Execute Script command to correctly convert document.all into JSON format
- Improved handling of bad element reference

Bump chromedriver version to 73.0.3683.20

---

install.js

The `extractDownload` path that handles copying a pre-downloaded, pre-extracted binary specified via `chromedriver_filepath` currently assumes that it should copy to a file named `chromedriver`, rather than using `chromedriver.exe` on Windows like the rest of the code expects.
Fixes #212

Add chromedriver_filepath support for direct exe paths on Windows

---

.npmignore
README.md
package.json
update.js

At the moment, it is a bit of a manual process to get a new Chromedriver release, pulled into this project and published to NPM.
It would be easier for the maintainer and consumers of the module if this could be more automated.
This PR offers a new npm script `npm run update-chromedriver` which will find the latest version of Chromedriver which is available. If there is a newer once available which is newer that what is currently in the project, it will
- bump version in lib/chromedriver.js
- bump package.json version
- git tag version
- git commit update message
If this script works well locally, we could look at getting it running on a cron schedule, once per day(maybe using Github Actions?). That way it should be easy to get the latest Chromedriver.

Automated Chromedriver updates

---

README.md

It would probably be more useful for readers to refer to a real version instead of the default of LATEST

Versioning LATEST => 75.0.3770.140

---

lib/chromedriver.js
package-lock.json
package.json

Chromedriver 78.0.3904.70 ([changelog](https://chromedriver.storage.googleapis.com/78.0.3904.70/notes.txt)) has been released for Chrome 78 ([release notes](https://blog.chromium.org/2019/09/chrome-78-beta-new-houdini-api-native.html)).

Bump ChromeDriver to 78.0.3904.70

---

install.js

Ref #72.
* For npm_config_tmp to work as (optional) override for the default
temporary directory, it has to be checked first, not last
in the chain of default-operator checks.
* Add support for XDG_CACHE_HOME which some XDG-compliant environments
will set to a directory that is persisted between CI runs and such.
The XDG Cache home concept is ideal for this purpose because
node-chromedriver takes care to clean up after itself and uses a
deterministic filename. As such, it won't grow out of control and can
be safely cached and persisted when XDG is provided.
This way, downstream users of node-chromedriver are not required to
set npm_config_tmp to a persisted directory, which can be undesirable
due to the inherit nature and expectation of a temp directory.
E.g. software tends to place files …

Support XDG_CACHE_HOME and make npm_config_tmp work

---

lib/chromedriver.js
package-lock.json
package.json

As of earlier today Chrome has moved their stable release to 79. The https://chromedriver.storage.googleapis.com/LATEST_RELEASE however did not get the update. To further the fun, Travis CI is pulling 79 as `stable`.
If possible, it'd be wonderful to update to chromedriver 79, publish a new package, and resolve the discrepancy with Travis.

Bump version to 79.0.0

---

README.md
install.js

Since #222 got closed and Chromium [explicitly discourages using `LATEST_RELEASE` in order to get the latest version](https://chromedriver.chromium.org/downloads/version-selection), I added a way to force the download of the latest version for a specific major release. This somewhat addresses the problem in #244.

Allow specifying the latest version for a specific major release

---

package-lock.json
package.json

Hi, I noticed the `https-proxy-agent` has newer versions with up-to-date dependencies, and seems like it doesn't contain changes that might break the current library usage:
- v4 to [v5](https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/5.0.0): Typescript rewrite
- v3 to [v4](https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/4.0.0): Require Node 6
- v2 to [v3](https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0): Remove Node 4/5 support
The current version supports any [engine >= 6](https://github.com/TooTallNate/node-https-proxy-agent/blob/3.0.0/.travis.yml#L3), so we should we safe with this update.

[update-https-proxy-lib] Update https-proxy-agent lib to v5

---

install.js

Fix #289 
I have test this patch in mac book pro m1:
```
lifubang@bogon node-chromedriver % node ./install.js 
Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://npm.taobao.org/mirrors/chromedriver/87.0.4280.20/chromedriver_mac64.zip
Saving to file: /var/folders/h2/6c34nh_146q83y6lh0twr0s80000gn/T/87.0.4280.20/chromedriver/chromedriver_mac64.zip
Received 1026K...
Received 2066K...
Received 3106K...
Received 4146K...
Received 5186K...
Received 6226K...
Received 7266K...
Received 7712K total.
Extracting zip contents to /var/folders/h2/6c34nh_146q83y6lh0twr0s80000gn/T/87.0.4280.20/chromedriver.
Copying to target path /Users/lifubang/dev/github/node-chromedriver/lib/chromedriver
Fixing file permissions.
Done. …
```

let it works in mac book m1

---

lib/chromedriver.js
package-lock.json
package.json

The update script uses this URL: https://chromedriver.storage.googleapis.com/LATEST_RELEASE , which still points to version 89.x. However, version 90 is available, even though that URL has not yet updated: https://chromedriver.chromium.org/downloads
So, I temporarily hard-coded the version as `90.0.4430.24` (instead of using the `LATEST_RELEASE` alias) to produce this PR.

Bump version to 90.0.0

---

install.js

I noticed that using Node.js emulated with Rosetta made the script download the Intel version of the chromedriver instead of the Apple Silicon one. 
I've changed it the platform check so it can see what's the real processor architecture and download the chromedriver accordingly. 
I run browsers without emulation but not Node.js since some packages are still not compatible.
You need to be on an M1 Mac, this is how you do it:
Clone this PR:
````bash
git clone https://github.com/johnathafelix/node-chromedriver.git
cd node-chromedriver
npm install
````
Then, check if you can run Chromedriver:
````bash
./bin/chromedriver
````
If it shows output correctly, then it worked. This is the expected output (somewhat similar is ok):
````
Starting ChromeDriver 97.0.4692.71 …
```

Download chromedriver binary for Mac M1

---

lib/chromedriver.js
package.json

This bug https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999 is now fixed with a release of 98.0.4758.102.
TLDR: some keystrokes are broken in 98.0.4758.80  (e.g. DEL button behaves differently, the character of '\\' fails as unrecognized etc.). For example element.sendKeys(webdriver.Key.DELETE) doesn't work.

Bump to 98.0.4758.102

---

install.js

Fixes #357 
This fixes the `sysctl` call on Intel macs, where `sysctl` doesn't
output anything (in which case `stdout` is `null`).

fix: Check for stdout in sysctl

---

README.md

npm.taobao.org is deprecated
see details: https://npmmirror.com/

Update mirror url

---

README.md

This PR fixes a 404 link in the README where it was pointing to an Azure config file when the project probably switch to github action.

Fix build link in readme

---

.npmignore

I noticed in https://app.renovatebot.com/package-diff?name=chromedriver&from=107.0.2&to=107.0.3 that this file was added to the bundle, and I assumed it was accidental.

npm ignore tsconfig.json

---

lib/chromedriver.js

Use latest chromedriver version that fixes a bug in the chrome binary resolution and solves the error:
`An error occurred while creating a new ChromeDriver session: [WebDriverError] unknown error: cannot find Chrome binary`
See: https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30
and: https://bugs.chromium.org/p/chromium/issues/detail?id=1466427

Use latest chromedriver version 115.0.5790.170

---

install.js

Copying the binary no longer worked, unless the destination tmp folder already existed.
Steps to reproduce:
- rm -Rf /tmp/117.0.5938.92/chromedriver/
- CHROMEDRIVER_FILEPATH="/yourpathto/chromedriver" node node_modules/chromedriver/install.js
Failed with:
```
ChromeDriver installation failed Error: ENOENT: no such file or directory, copyfile '/tmp/chromedriver' -> '/tmp/117.0.5938.92/chromedriver/chromedriver-linux64/chromedriver'
at Object.copyFileSync (node:fs:2894:3)
at extractDownload (/home/anastasios/Sources/cloud/web/node_modules/chromedriver/install.js:364:8)
at install (/home/anastasios/Sources/cloud/web/node_modules/chromedriver/install.js:70:13)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errno: -2,
syscall: 'copyfile',
code: 'ENOENT',
path: …
```

Creates the intermediate tmp folder before attempting to copy CHROMEDRIVER_FILEPATH to it.

---

README.md
install.js

This PR adds initial support for RISC-V 64-bit systems to the `chromedriver` npm package. Since the Chrome team doesn’t provide an official RISC-V binary, this change ensures the package can still install on RISC-V by requiring a local binary via `--chromedriver_filepath`.
- **install.js**: Added a check for `process.arch === 'riscv64'`. If detected and `--chromedriver_filepath` isn’t provided, it throws a helpful error:
- **README.md**: added Instruction for riscv users.
- Tested on my RISC-V system:
- Without `--chromedriver_filepath`: Fails with the error message.
- Non-RISC-V systems should be unaffected.

Add RISC-V 64-bit Support with --chromedriver_filepath Check

---

package-lock.json
package.json

This PR addresses a high-level security vulnerability reported for axios for versions 1.11.0 and below: [CVE-2025-58754](https://www.cve.org/CVERecord?id=CVE-2025-58754).
Axios has been upgraded to use a minimum version of 1.12.0, which patches the vulnerability.

chore: upgrade axios to 1.12.0 to address CVE-2025-58754
