giggio/node-chromedriver

install.js
http://chromedriver.storage.googleapis.com/index.html?path=2.23/
=> 2.23 only has a 64bit version for mac

lib/chromedriver.js, package.json
=> Updating to support Chromedriver 2.25

lib/chromedriver.js, package.json
http://chromedriver.storage.googleapis.com/2.26/notes.txt
=> Version bump to 2.26.0 and update to chromedriver 2.26.

lib/chromedriver.js, package.json
Updating to latest version of chrome driver -- https://chromedriver.storage.googleapis.com/2.29/notes.txt
=> Updating version to 2.29, release Apr 4 2017

README.md, install.js
=> Use Agent-User from npm config

lib/chromedriver.js, package.json
Chromedriver 2.34 and version bump to 2.34.0
=>  Chromedriver 2.34 and version bump to 2.34.0

lib/chromedriver.js, package.json
=>  bump version to 2.35

lib/chromedriver.js, package.json
=> Bump version to 2.36.0

lib/chromedriver.js, package.json
I copied what previous committers did.  😄
=> Bump chromedriver version to 2.39

lib/chromedriver.js, package.json
I guess there were enough important things to fix that they released another version a week later.
=> Bump chromedriver version to 2.40

lib/chromedriver.js, package.json
2.41 notes: https://chromedriver.storage.googleapis.com/2.41/notes.txt
=> Bump version to 2.41

lib/chromedriver.js, package-lock.json, package.json
Changed chromedriver version from 2.42 to 2.43
=> updated chromedriver version to 2.43

install.js
I add a step to validate the binary file if it is existing before download file. I let the process exit directly if the binary file is available.
It mainly to solve #72. I take the way in [the comment](https://github.com/giggio/node-chromedriver/issues/72#issuecomment-378281384). I think it could reduce some issues due to the network. Could you consider that is it worth to be merged?
=> Avoid downloading again if the file is existing

lib/chromedriver.js, package-lock.json, package.json
Looks like a new major version of chrome got released in the last couple days that requires a chromedriver bump.
=> Bump chromdriver version to 74.0.3729.6

lib/chromedriver.js, package-lock.json, package.json
It is stable now:
https://sites.google.com/a/chromium.org/chromedriver/home
=> Bumped to version 75.0.3770.8

README.md
As per this line of code:
https://github.com/giggio/node-chromedriver/blob/master/install.js#L20
=> Update docs on default URL

lib/chromedriver.js, package-lock.json, package.json
They've released a new stable version: 76!
=> Bumped chromedriver version to 76.0.3809.68

lib/chromedriver.js, package-lock.json, package.json
=> bump chromedriver to 77.0.3865.40

install.js, package-lock.json, package.json
Fixed issue #255 by use of https-proxy-agent as workaround.
=> Introduced workaround for https-url combined with a proxy.

lib/chromedriver.js, package-lock.json, package.json
=> Bump version to 84.0.0

lib/chromedriver.js, package-lock.json, package.json
Updating default driver to match recently released Chrome 85
=> update default driver version to 85.x, bump module to 85.0.0

lib/chromedriver.js, package-lock.json, package.json
Update default driver to use patch fix for the issue: [Chrome 85 no longer allows graceful interaction with windows when an alert dialog is open](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3578)
=> Bump to 85.0.1 with driver patch fix

install.js
=> modify a comparing bug for macOSX M1 platform

lib/chromedriver.js, package.json
Hi, this adds an update for latest chrome version.
https://chromereleases.googleblog.com/2021/11/stable-channel-update-for-desktop.html
=> Update ChromeDriver to v96

lib/chromedriver.js, package-lock.json, package.json
hi, 
bump to chrome version 97
https://chromereleases.googleblog.com/2022/01/stable-channel-update-for-desktop.html
=> Bump version to 97.0.0

install.js
> originally submitted as https://github.com/giggio/node-chromedriver/pull/333 but stalebot closed it while I was on vacation
There is a bug in the install script where if a 404 or other error status code is received with a response body then the install script will attempt to download the contents of the response. The code listens for the `finish` event to know when the stream is done, but this event is only applicable to `Writable` streams and is not fired for `Readable` streams (at least not in modern versions of Node, I think I remember this changing at some point in the past).
This causes the script to exit with a 0 status code because the promise on line 259 of the script never resolves and node runs out of work and exits assuming all is well, causing chromedriver to silently fail …
=> [install] properly handle error status codes

lib/chromedriver.js, package-lock.json, package.json
I ran the `update-chromedriver` command.
Thanks for your work on this package!
=> Bump version to 99.0.4844.51

install.js, package-lock.json, package.json
Fixes #384 with backwards compatibility
=> Fix apple silicon arch for newer chromedriver build schema

lib/chromedriver.js, package-lock.json, package.json
@giggio: This updates to Chrome 107, released today (addressing #388)
=> Bump version to 107.0.0

README.md
Hi there,
In the first paragraph mentioning it, the property for the binary url appears to be wrong.
Kind regards
=> fix binaries url property

lib/chromedriver.js, package-lock.json, package.json
@giggio : This updates to Chrome 116, released on 08.15.2023
=> Bump version to 116.0.0
